# Generated by Django 5.1.1 on 2025-02-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='medicinesale',
            options={'verbose_name': 'Medicine Sale', 'verbose_name_plural': 'Medicine Sales'},
        ),
        migrations.AlterModelOptions(
            name='medicinestock',
            options={'verbose_name': 'Medicine Stock', 'verbose_name_plural': 'Medicine Stocks'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Alert', 'verbose_name_plural': 'Stock Alerts'},
        ),
    ]
