# Generated by Django 5.1.1 on 2025-03-26 20:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_medicine_options_alter_medicinesale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Purchase price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
