# Generated by Django 5.1.1 on 2025-03-26 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_medicinestock_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('stock_add', 'Stock Added'), ('stock_update', 'Stock Updated'), ('medicine_add', 'Medicine Added'), ('medicine_edit', 'Medicine Edited'), ('medicine_delete', 'Medicine Deleted'), ('shop_add', 'Shop Added'), ('shop_edit', 'Shop Edited'), ('shop_delete', 'Shop Deleted'), ('alert_resolved', 'Alert Resolved'), ('other', 'Other Action')], max_length=20)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.medicine')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.shop')),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='inventory_t_action__abfbf5_idx'), models.Index(fields=['created_at'], name='inventory_t_created_019961_idx')],
            },
        ),
    ]
